/**
 * ML Query Router - Auto-generated from Decision Tree
 *
 * DO NOT EDIT - This file is auto-generated by train.js
 * Generated: 2026-01-06T04:37:54.500Z
 *
 * Target: <50μs inference
 */

export interface MLRouteResult {
  mode: 'lexical' | 'semantic' | 'structural' | 'hybrid';
  confidence: number;
  tier: number;
  method: string;
}

/**
 * Feature indices for reference:
 *  0: hasCamelBoundary
 *  1: hasUnderscoreWord
 *  2: startsWithUppercase
 *  3: hasConsecutiveUppercase
 *  4: isSingleToken
 *  5: hasDotNotation
 *  6: hasParentheses
 *  7: hasFileExtension
 *  8: hasPathSeparator
 *  9: tokenCount
 * 10: avgTokenLength
 * 11: uppercaseRatio
 * 12: digitRatio
 * 13: nonAsciiRatio
 * 14: hasNonLatinScript
 * 15: hasCallerPattern
 * 16: hasCalleePattern
 * 17: hasImplementationPattern
 * 18: hasImpactPattern
 * 19: hasIdentifierInQuery
 * 20: startsWithQuestionWord
 * 21: endsWithQuestionMark
 * 22: hasSemanticConceptWord
 * 23: hasExplanationRequest
 * 24: hasHowDoesWorkPattern
 * 25: hasNonAsciiIdentifier
 * 26: hasMixedScriptToken
 * 27: hasStructuralKeywordNonEn
 * 28: hasSemanticKeywordNonEn
 */

/**
 * Route query using trained ML model.
 * @param features - 25-element feature vector from extractAllFeatures()
 * @returns Routing decision with confidence
 */
export function routeQueryML(features: Float32Array | number[]): MLRouteResult {
  if (features[4] /* isSingleToken */ <= 0.500000) {
    if (features[0] /* hasCamelBoundary */ <= 0.500000) {
      if (features[13] /* nonAsciiRatio */ <= 0.344289) {
        if (features[11] /* uppercaseRatio */ <= 0.030777) {
          if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
            if (features[13] /* nonAsciiRatio */ <= 0.175493) {
              if (features[10] /* avgTokenLength */ <= 6.900000) {
                if (features[23] /* hasExplanationRequest */ <= 0.500000) {
                  if (features[9] /* tokenCount */ <= 2.500000) {
                    if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
                      return { mode: 'hybrid', confidence: 0.5714, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 6.366667) {
                      return { mode: 'semantic', confidence: 0.9282, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                if (features[23] /* hasExplanationRequest */ <= 0.500000) {
                  if (features[9] /* tokenCount */ <= 3.500000) {
                    if (features[9] /* tokenCount */ <= 2.500000) {
                      return { mode: 'semantic', confidence: 0.6512, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.7727, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 7.625000) {
                      return { mode: 'semantic', confidence: 0.8947, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 8.833333) {
                    if (features[10] /* avgTokenLength */ <= 7.708333) {
                      return { mode: 'semantic', confidence: 0.7857, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.9259, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              }
            } else {
              if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
                if (features[14] /* hasNonLatinScript */ <= 0.500000) {
                  if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
                    if (features[9] /* tokenCount */ <= 3.500000) {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 0.6667, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[13] /* nonAsciiRatio */ <= 0.310606) {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[9] /* tokenCount */ <= 2.500000) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[9] /* tokenCount */ <= 3.500000) {
                      return { mode: 'hybrid', confidence: 0.7188, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.6429, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                if (features[9] /* tokenCount */ <= 4.500000) {
                  if (features[10] /* avgTokenLength */ <= 6.125000) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[10] /* avgTokenLength */ <= 7.000000) {
                      return { mode: 'hybrid', confidence: 0.6667, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            }
          } else {
            if (features[13] /* nonAsciiRatio */ <= 0.205263) {
              if (features[10] /* avgTokenLength */ <= 10.750000) {
                if (features[13] /* nonAsciiRatio */ <= 0.028992) {
                  if (features[10] /* avgTokenLength */ <= 5.291667) {
                    if (features[10] /* avgTokenLength */ <= 5.125000) {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[13] /* nonAsciiRatio */ <= 0.044466) {
                    if (features[13] /* nonAsciiRatio */ <= 0.042572) {
                      return { mode: 'semantic', confidence: 0.8824, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.6000, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[13] /* nonAsciiRatio */ <= 0.114379) {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.8837, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                if (features[9] /* tokenCount */ <= 2.500000) {
                  if (features[13] /* nonAsciiRatio */ <= 0.145833) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[25] /* hasNonAsciiIdentifier */ <= 0.500000) {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                }
              }
            } else {
              if (features[10] /* avgTokenLength */ <= 5.125000) {
                if (features[10] /* avgTokenLength */ <= 4.650000) {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[9] /* tokenCount */ <= 4.500000) {
                    return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              } else {
                if (features[13] /* nonAsciiRatio */ <= 0.329167) {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[26] /* hasMixedScriptToken */ <= 0.500000) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[10] /* avgTokenLength */ <= 9.750000) {
                      return { mode: 'semantic', confidence: 0.7500, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              }
            }
          }
        } else {
          if (features[10] /* avgTokenLength */ <= 6.416667) {
            if (features[26] /* hasMixedScriptToken */ <= 0.500000) {
              if (features[13] /* nonAsciiRatio */ <= 0.299107) {
                if (features[1] /* hasUnderscoreWord */ <= 0.500000) {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            } else {
              if (features[3] /* hasConsecutiveUppercase */ <= 0.500000) {
                if (features[11] /* uppercaseRatio */ <= 0.160281) {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            }
          } else {
            if (features[10] /* avgTokenLength */ <= 8.416667) {
              if (features[10] /* avgTokenLength */ <= 6.875000) {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[23] /* hasExplanationRequest */ <= 0.500000) {
                  if (features[9] /* tokenCount */ <= 3.500000) {
                    if (features[10] /* avgTokenLength */ <= 7.500000) {
                      return { mode: 'semantic', confidence: 0.8889, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.5333, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            } else {
              if (features[13] /* nonAsciiRatio */ <= 0.124521) {
                if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                  if (features[9] /* tokenCount */ <= 2.500000) {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
                      return { mode: 'semantic', confidence: 0.7143, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[9] /* tokenCount */ <= 3.500000) {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              } else {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            }
          }
        }
      } else {
        if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
          if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
            if (features[9] /* tokenCount */ <= 3.500000) {
              if (features[10] /* avgTokenLength */ <= 7.833333) {
                if (features[15] /* hasCallerPattern */ <= 0.500000) {
                  if (features[9] /* tokenCount */ <= 2.500000) {
                    if (features[10] /* avgTokenLength */ <= 4.250000) {
                      return { mode: 'semantic', confidence: 0.7143, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[3] /* hasConsecutiveUppercase */ <= 0.500000) {
                      return { mode: 'structural', confidence: 0.7589, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
                    if (features[13] /* nonAsciiRatio */ <= 0.584928) {
                      return { mode: 'lexical', confidence: 0.6364, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[13] /* nonAsciiRatio */ <= 0.552778) {
                      return { mode: 'structural', confidence: 0.6667, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                if (features[13] /* nonAsciiRatio */ <= 0.618037) {
                  if (features[16] /* hasCalleePattern */ <= 0.500000) {
                    if (features[14] /* hasNonLatinScript */ <= 0.500000) {
                      return { mode: 'hybrid', confidence: 0.4375, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 0.8125, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 11.833333) {
                    if (features[27] /* hasStructuralKeywordNonEn */ <= 0.500000) {
                      return { mode: 'structural', confidence: 0.3243, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 0.6279, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 12.833333) {
                      return { mode: 'structural', confidence: 0.5385, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 0.6154, tier: 5, method: 'ml' };
                    }
                  }
                }
              }
            } else {
              if (features[14] /* hasNonLatinScript */ <= 0.500000) {
                if (features[18] /* hasImpactPattern */ <= 0.500000) {
                  if (features[10] /* avgTokenLength */ <= 8.500000) {
                    if (features[10] /* avgTokenLength */ <= 6.325000) {
                      return { mode: 'structural', confidence: 0.6765, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 0.4583, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
                      return { mode: 'hybrid', confidence: 0.5000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.8000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[13] /* nonAsciiRatio */ <= 0.527116) {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[10] /* avgTokenLength */ <= 7.500000) {
                      return { mode: 'structural', confidence: 0.6667, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
                  if (features[10] /* avgTokenLength */ <= 6.083333) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[10] /* avgTokenLength */ <= 7.125000) {
                      return { mode: 'semantic', confidence: 0.3333, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.4063, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[13] /* nonAsciiRatio */ <= 0.660920) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[10] /* avgTokenLength */ <= 7.875000) {
                      return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              }
            }
          } else {
            if (features[9] /* tokenCount */ <= 3.500000) {
              if (features[13] /* nonAsciiRatio */ <= 0.818122) {
                if (features[14] /* hasNonLatinScript */ <= 0.500000) {
                  if (features[10] /* avgTokenLength */ <= 11.500000) {
                    if (features[13] /* nonAsciiRatio */ <= 0.531015) {
                      return { mode: 'hybrid', confidence: 0.9412, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 0.6875, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                if (features[10] /* avgTokenLength */ <= 9.666667) {
                  return { mode: 'lexical', confidence: 0.6667, tier: 5, method: 'ml' };
                } else {
                  if (features[10] /* avgTokenLength */ <= 10.166667) {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              }
            } else {
              if (features[13] /* nonAsciiRatio */ <= 0.513889) {
                if (features[10] /* avgTokenLength */ <= 8.625000) {
                  if (features[13] /* nonAsciiRatio */ <= 0.346990) {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[13] /* nonAsciiRatio */ <= 0.390873) {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.6000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                if (features[10] /* avgTokenLength */ <= 6.500000) {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            }
          }
        } else {
          if (features[9] /* tokenCount */ <= 3.500000) {
            if (features[10] /* avgTokenLength */ <= 8.416667) {
              if (features[13] /* nonAsciiRatio */ <= 0.566964) {
                if (features[14] /* hasNonLatinScript */ <= 0.500000) {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[10] /* avgTokenLength */ <= 6.833333) {
                    if (features[10] /* avgTokenLength */ <= 5.166667) {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.6667, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              } else {
                if (features[10] /* avgTokenLength */ <= 6.583333) {
                  if (features[10] /* avgTokenLength */ <= 3.833333) {
                    if (features[10] /* avgTokenLength */ <= 3.500000) {
                      return { mode: 'semantic', confidence: 0.8333, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.6364, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 6.166667) {
                      return { mode: 'semantic', confidence: 0.6250, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[13] /* nonAsciiRatio */ <= 0.850000) {
                    if (features[10] /* avgTokenLength */ <= 7.583333) {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 0.7143, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[13] /* nonAsciiRatio */ <= 0.914855) {
                      return { mode: 'semantic', confidence: 0.7778, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 0.7143, tier: 5, method: 'ml' };
                    }
                  }
                }
              }
            } else {
              if (features[13] /* nonAsciiRatio */ <= 0.929803) {
                if (features[11] /* uppercaseRatio */ <= 0.027047) {
                  if (features[13] /* nonAsciiRatio */ <= 0.531136) {
                    if (features[9] /* tokenCount */ <= 2.500000) {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.7647, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
                      return { mode: 'semantic', confidence: 0.8000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 0.9000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[2] /* startsWithUppercase */ <= 0.500000) {
                    if (features[13] /* nonAsciiRatio */ <= 0.440805) {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 0.5000, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 9.833333) {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.6000, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                if (features[9] /* tokenCount */ <= 2.500000) {
                  if (features[10] /* avgTokenLength */ <= 13.500000) {
                    if (features[26] /* hasMixedScriptToken */ <= 0.500000) {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 0.7143, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 14.750000) {
                      return { mode: 'lexical', confidence: 0.5000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 9.833333) {
                    return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'lexical', confidence: 0.5000, tier: 5, method: 'ml' };
                  }
                }
              }
            }
          } else {
            if (features[10] /* avgTokenLength */ <= 6.875000) {
              if (features[10] /* avgTokenLength */ <= 4.625000) {
                return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
              } else {
                if (features[13] /* nonAsciiRatio */ <= 0.897368) {
                  if (features[14] /* hasNonLatinScript */ <= 0.500000) {
                    if (features[10] /* avgTokenLength */ <= 6.300000) {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 5.500000) {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              }
            } else {
              if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
                if (features[13] /* nonAsciiRatio */ <= 0.447861) {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
                    if (features[10] /* avgTokenLength */ <= 7.875000) {
                      return { mode: 'hybrid', confidence: 0.5385, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.8182, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              } else {
                return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            }
          }
        }
      }
    } else {
      if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
        if (features[14] /* hasNonLatinScript */ <= 0.500000) {
          if (features[2] /* startsWithUppercase */ <= 0.500000) {
            if (features[9] /* tokenCount */ <= 3.500000) {
              if (features[27] /* hasStructuralKeywordNonEn */ <= 0.500000) {
                if (features[10] /* avgTokenLength */ <= 8.833333) {
                  return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[11] /* uppercaseRatio */ <= 0.072751) {
                    if (features[10] /* avgTokenLength */ <= 9.833333) {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 0.9412, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 10.500000) {
                      return { mode: 'structural', confidence: 0.8462, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                if (features[10] /* avgTokenLength */ <= 8.166667) {
                  return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[10] /* avgTokenLength */ <= 9.500000) {
                    if (features[13] /* nonAsciiRatio */ <= 0.019231) {
                      return { mode: 'lexical', confidence: 0.8333, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 10.333333) {
                      return { mode: 'structural', confidence: 0.6667, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              }
            } else {
              if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
                if (features[9] /* tokenCount */ <= 4.500000) {
                  if (features[11] /* uppercaseRatio */ <= 0.154762) {
                    if (features[11] /* uppercaseRatio */ <= 0.067816) {
                      return { mode: 'structural', confidence: 0.6923, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 0.9038, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[18] /* hasImpactPattern */ <= 0.500000) {
                    if (features[10] /* avgTokenLength */ <= 6.300000) {
                      return { mode: 'hybrid', confidence: 0.7500, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.7778, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              } else {
                if (features[10] /* avgTokenLength */ <= 7.125000) {
                  if (features[10] /* avgTokenLength */ <= 6.100000) {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[9] /* tokenCount */ <= 4.500000) {
                      return { mode: 'structural', confidence: 0.6000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 0.6667, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 7.875000) {
                    if (features[10] /* avgTokenLength */ <= 7.625000) {
                      return { mode: 'semantic', confidence: 0.7000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 0.6667, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[11] /* uppercaseRatio */ <= 0.121582) {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              }
            }
          } else {
            if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
              if (features[11] /* uppercaseRatio */ <= 0.139291) {
                if (features[11] /* uppercaseRatio */ <= 0.075962) {
                  if (features[10] /* avgTokenLength */ <= 12.333333) {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 7.833333) {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[13] /* nonAsciiRatio */ <= 0.033370) {
                      return { mode: 'structural', confidence: 0.6400, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                if (features[9] /* tokenCount */ <= 2.500000) {
                  return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[13] /* nonAsciiRatio */ <= 0.154074) {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                  }
                }
              }
            } else {
              if (features[11] /* uppercaseRatio */ <= 0.089572) {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[11] /* uppercaseRatio */ <= 0.096875) {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[11] /* uppercaseRatio */ <= 0.129085) {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                  }
                }
              }
            }
          }
        } else {
          if (features[2] /* startsWithUppercase */ <= 0.500000) {
            if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
              if (features[11] /* uppercaseRatio */ <= 0.149733) {
                if (features[11] /* uppercaseRatio */ <= 0.077961) {
                  if (features[13] /* nonAsciiRatio */ <= 0.540568) {
                    if (features[13] /* nonAsciiRatio */ <= 0.485294) {
                      return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            } else {
              if (features[10] /* avgTokenLength */ <= 7.125000) {
                if (features[13] /* nonAsciiRatio */ <= 0.236111) {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            }
          } else {
            if (features[13] /* nonAsciiRatio */ <= 0.467437) {
              return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
            } else {
              if (features[13] /* nonAsciiRatio */ <= 0.614815) {
                if (features[13] /* nonAsciiRatio */ <= 0.531373) {
                  if (features[9] /* tokenCount */ <= 2.500000) {
                    if (features[10] /* avgTokenLength */ <= 9.500000) {
                      return { mode: 'lexical', confidence: 0.5000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            }
          }
        }
      } else {
        if (features[13] /* nonAsciiRatio */ <= 0.239048) {
          if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
            if (features[10] /* avgTokenLength */ <= 11.833333) {
              if (features[10] /* avgTokenLength */ <= 6.583333) {
                if (features[11] /* uppercaseRatio */ <= 0.078462) {
                  return { mode: 'hybrid', confidence: 0.6667, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            } else {
              return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
            }
          } else {
            if (features[10] /* avgTokenLength */ <= 9.375000) {
              return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
            } else {
              return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
            }
          }
        } else {
          if (features[10] /* avgTokenLength */ <= 10.500000) {
            if (features[10] /* avgTokenLength */ <= 8.500000) {
              if (features[10] /* avgTokenLength */ <= 8.166667) {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            } else {
              return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
            }
          } else {
            return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
          }
        }
      }
    }
  } else {
    if (features[26] /* hasMixedScriptToken */ <= 0.500000) {
      if (features[10] /* avgTokenLength */ <= 4.500000) {
        if (features[13] /* nonAsciiRatio */ <= 0.500000) {
          return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
        } else {
          if (features[10] /* avgTokenLength */ <= 3.500000) {
            return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
          } else {
            if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
              return { mode: 'semantic', confidence: 0.6176, tier: 5, method: 'ml' };
            } else {
              return { mode: 'semantic', confidence: 0.8000, tier: 5, method: 'ml' };
            }
          }
        }
      } else {
        if (features[11] /* uppercaseRatio */ <= 0.020833) {
          if (features[14] /* hasNonLatinScript */ <= 0.500000) {
            if (features[1] /* hasUnderscoreWord */ <= 0.500000) {
              if (features[19] /* hasIdentifierInQuery */ <= 0.500000) {
                return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[10] /* avgTokenLength */ <= 5.500000) {
                  if (features[13] /* nonAsciiRatio */ <= 0.500000) {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 10.500000) {
                    if (features[13] /* nonAsciiRatio */ <= 0.500000) {
                      return { mode: 'lexical', confidence: 0.5000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 0.7200, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 20.500000) {
                      return { mode: 'lexical', confidence: 0.4821, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 0.8000, tier: 5, method: 'ml' };
                    }
                  }
                }
              }
            } else {
              return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
            }
          } else {
            if (features[10] /* avgTokenLength */ <= 12.500000) {
              if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                if (features[10] /* avgTokenLength */ <= 8.500000) {
                  if (features[10] /* avgTokenLength */ <= 6.500000) {
                    if (features[10] /* avgTokenLength */ <= 5.500000) {
                      return { mode: 'lexical', confidence: 0.5714, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 0.6667, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 7.500000) {
                      return { mode: 'hybrid', confidence: 0.7143, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 0.5000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[13] /* nonAsciiRatio */ <= 0.958333) {
                    return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[10] /* avgTokenLength */ <= 9.500000) {
                      return { mode: 'lexical', confidence: 0.7500, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 0.7381, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                if (features[10] /* avgTokenLength */ <= 6.500000) {
                  return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            } else {
              if (features[10] /* avgTokenLength */ <= 16.500000) {
                if (features[10] /* avgTokenLength */ <= 13.500000) {
                  return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[10] /* avgTokenLength */ <= 15.500000) {
                    if (features[10] /* avgTokenLength */ <= 14.500000) {
                      return { mode: 'lexical', confidence: 0.9048, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'lexical', confidence: 0.8667, tier: 5, method: 'ml' };
                  }
                }
              } else {
                if (features[10] /* avgTokenLength */ <= 20.500000) {
                  if (features[10] /* avgTokenLength */ <= 17.500000) {
                    return { mode: 'lexical', confidence: 0.9091, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 21.500000) {
                    if (features[13] /* nonAsciiRatio */ <= 0.952381) {
                      return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 0.7500, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              }
            }
          }
        } else {
          if (features[11] /* uppercaseRatio */ <= 0.121324) {
            if (features[11] /* uppercaseRatio */ <= 0.102632) {
              if (features[11] /* uppercaseRatio */ <= 0.087121) {
                if (features[10] /* avgTokenLength */ <= 17.500000) {
                  if (features[10] /* avgTokenLength */ <= 16.500000) {
                    if (features[10] /* avgTokenLength */ <= 15.500000) {
                      return { mode: 'lexical', confidence: 0.9500, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'lexical', confidence: 0.8571, tier: 5, method: 'ml' };
                  }
                } else {
                  return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            } else {
              if (features[5] /* hasDotNotation */ <= 0.500000) {
                if (features[2] /* startsWithUppercase */ <= 0.500000) {
                  if (features[10] /* avgTokenLength */ <= 13.500000) {
                    return { mode: 'lexical', confidence: 0.8333, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 17.500000) {
                    if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                      return { mode: 'lexical', confidence: 0.8000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              } else {
                return { mode: 'lexical', confidence: 0.5000, tier: 5, method: 'ml' };
              }
            }
          } else {
            if (features[2] /* startsWithUppercase */ <= 0.500000) {
              if (features[11] /* uppercaseRatio */ <= 0.160256) {
                return { mode: 'lexical', confidence: 0.5000, tier: 5, method: 'ml' };
              } else {
                return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            } else {
              return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
            }
          }
        }
      }
    } else {
      if (features[11] /* uppercaseRatio */ <= 0.033333) {
        if (features[13] /* nonAsciiRatio */ <= 0.821429) {
          if (features[10] /* avgTokenLength */ <= 18.500000) {
            if (features[10] /* avgTokenLength */ <= 11.500000) {
              if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                if (features[10] /* avgTokenLength */ <= 8.500000) {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                if (features[10] /* avgTokenLength */ <= 7.500000) {
                  return { mode: 'semantic', confidence: 0.7500, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            } else {
              return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
            }
          } else {
            if (features[10] /* avgTokenLength */ <= 23.500000) {
              if (features[13] /* nonAsciiRatio */ <= 0.498747) {
                if (features[13] /* nonAsciiRatio */ <= 0.441388) {
                  if (features[1] /* hasUnderscoreWord */ <= 0.500000) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[10] /* avgTokenLength */ <= 20.000000) {
                      return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.6667, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            } else {
              return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
            }
          }
        } else {
          if (features[10] /* avgTokenLength */ <= 10.500000) {
            if (features[10] /* avgTokenLength */ <= 6.500000) {
              if (features[10] /* avgTokenLength */ <= 5.500000) {
                return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                }
              }
            } else {
              if (features[10] /* avgTokenLength */ <= 8.500000) {
                if (features[10] /* avgTokenLength */ <= 7.500000) {
                  return { mode: 'semantic', confidence: 0.6000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'semantic', confidence: 0.6667, tier: 5, method: 'ml' };
                }
              } else {
                if (features[10] /* avgTokenLength */ <= 9.500000) {
                  return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                }
              }
            }
          } else {
            if (features[10] /* avgTokenLength */ <= 17.500000) {
              if (features[10] /* avgTokenLength */ <= 15.500000) {
                if (features[10] /* avgTokenLength */ <= 13.500000) {
                  if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                    if (features[10] /* avgTokenLength */ <= 11.500000) {
                      return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 11.500000) {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                    if (features[10] /* avgTokenLength */ <= 14.500000) {
                      return { mode: 'structural', confidence: 0.6000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 0.6250, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              } else {
                if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                  if (features[10] /* avgTokenLength */ <= 16.500000) {
                    if (features[27] /* hasStructuralKeywordNonEn */ <= 0.500000) {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 0.7500, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'semantic', confidence: 0.3333, tier: 5, method: 'ml' };
                  }
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            } else {
              if (features[10] /* avgTokenLength */ <= 18.500000) {
                if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                  return { mode: 'structural', confidence: 0.6667, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            }
          }
        }
      } else {
        if (features[14] /* hasNonLatinScript */ <= 0.500000) {
          if (features[13] /* nonAsciiRatio */ <= 0.303846) {
            if (features[11] /* uppercaseRatio */ <= 0.190909) {
              return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
            } else {
              if (features[10] /* avgTokenLength */ <= 12.500000) {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[10] /* avgTokenLength */ <= 14.500000) {
                  return { mode: 'lexical', confidence: 0.5000, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            }
          } else {
            return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
          }
        } else {
          if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
            if (features[27] /* hasStructuralKeywordNonEn */ <= 0.500000) {
              if (features[10] /* avgTokenLength */ <= 17.500000) {
                return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[13] /* nonAsciiRatio */ <= 0.270468) {
                  if (features[13] /* nonAsciiRatio */ <= 0.162281) {
                    return { mode: 'structural', confidence: 0.5000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            } else {
              if (features[2] /* startsWithUppercase */ <= 0.500000) {
                if (features[13] /* nonAsciiRatio */ <= 0.171569) {
                  return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                } else {
                  if (features[10] /* avgTokenLength */ <= 16.500000) {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[10] /* avgTokenLength */ <= 21.000000) {
                      return { mode: 'structural', confidence: 0.7000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                if (features[25] /* hasNonAsciiIdentifier */ <= 0.500000) {
                  if (features[10] /* avgTokenLength */ <= 15.500000) {
                    return { mode: 'structural', confidence: 0.6667, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[13] /* nonAsciiRatio */ <= 0.244444) {
                    if (features[13] /* nonAsciiRatio */ <= 0.193498) {
                      return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 0.6667, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              }
            }
          } else {
            if (features[10] /* avgTokenLength */ <= 17.000000) {
              return { mode: 'semantic', confidence: 0.5000, tier: 5, method: 'ml' };
            } else {
              return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
            }
          }
        }
      }
    }
  }
}

export default routeQueryML;
