/**
 * ML Query Router - Auto-generated from Decision Tree
 *
 * DO NOT EDIT - This file is auto-generated by train.js
 * Generated: 2026-01-05T15:35:16.960Z
 *
 * Target: <50μs inference
 */

export interface MLRouteResult {
  mode: 'lexical' | 'semantic' | 'structural' | 'hybrid';
  confidence: number;
  tier: number;
  method: string;
}

/**
 * Feature indices for reference:
 *  0: hasCamelBoundary
 *  1: hasUnderscoreWord
 *  2: startsWithUppercase
 *  3: hasConsecutiveUppercase
 *  4: isSingleToken
 *  5: hasDotNotation
 *  6: hasParentheses
 *  7: hasFileExtension
 *  8: hasPathSeparator
 *  9: tokenCount
 * 10: avgTokenLength
 * 11: uppercaseRatio
 * 12: digitRatio
 * 13: nonAsciiRatio
 * 14: hasNonLatinScript
 * 15: hasCallerPattern
 * 16: hasCalleePattern
 * 17: hasImplementationPattern
 * 18: hasImpactPattern
 * 19: hasIdentifierInQuery
 * 20: startsWithQuestionWord
 * 21: endsWithQuestionMark
 * 22: hasSemanticConceptWord
 * 23: hasExplanationRequest
 * 24: hasHowDoesWorkPattern
 * 25: hasNonAsciiIdentifier
 * 26: hasMixedScriptToken
 * 27: hasStructuralKeywordNonEn
 * 28: hasSemanticKeywordNonEn
 */

/**
 * Route query using trained ML model.
 * @param features - 25-element feature vector from extractAllFeatures()
 * @returns Routing decision with confidence
 */
export function routeQueryML(features: Float32Array | number[]): MLRouteResult {
  if (features[9] /* tokenCount */ <= 1.500000) {
    if (features[26] /* hasMixedScriptToken */ <= 0.500000) {
      return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
    } else {
      if (features[27] /* hasStructuralKeywordNonEn */ <= 0.500000) {
        if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
          if (features[10] /* avgTokenLength */ <= 13.500000) {
            if (features[0] /* hasCamelBoundary */ <= 0.500000) {
              if (features[13] /* nonAsciiRatio */ <= 0.730769) {
                return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            } else {
              return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
            }
          } else {
            if (features[14] /* hasNonLatinScript */ <= 0.500000) {
              return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
            } else {
              if (features[13] /* nonAsciiRatio */ <= 0.133929) {
                return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[0] /* hasCamelBoundary */ <= 0.500000) {
                  if (features[13] /* nonAsciiRatio */ <= 0.617647) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            }
          }
        } else {
          if (features[13] /* nonAsciiRatio */ <= 0.821429) {
            return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
          } else {
            if (features[10] /* avgTokenLength */ <= 9.000000) {
              return { mode: 'lexical', confidence: 1.0000, tier: 5, method: 'ml' };
            } else {
              return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
            }
          }
        }
      } else {
        return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
      }
    }
  } else {
    if (features[27] /* hasStructuralKeywordNonEn */ <= 0.500000) {
      if (features[0] /* hasCamelBoundary */ <= 0.500000) {
        if (features[13] /* nonAsciiRatio */ <= 0.119430) {
          return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
        } else {
          if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
            if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
              if (features[14] /* hasNonLatinScript */ <= 0.500000) {
                if (features[15] /* hasCallerPattern */ <= 0.500000) {
                  if (features[10] /* avgTokenLength */ <= 8.500000) {
                    if (features[13] /* nonAsciiRatio */ <= 0.471217) {
                      return { mode: 'structural', confidence: 0.6974, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 0.9608, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[17] /* hasImplementationPattern */ <= 0.500000) {
                      return { mode: 'hybrid', confidence: 0.7143, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                if (features[13] /* nonAsciiRatio */ <= 0.974359) {
                  if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
                    if (features[13] /* nonAsciiRatio */ <= 0.797431) {
                      return { mode: 'semantic', confidence: 0.5405, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[9] /* tokenCount */ <= 2.500000) {
                    return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    if (features[10] /* avgTokenLength */ <= 11.500000) {
                      return { mode: 'structural', confidence: 0.7143, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 0.8750, tier: 5, method: 'ml' };
                    }
                  }
                }
              }
            } else {
              if (features[9] /* tokenCount */ <= 2.500000) {
                return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[26] /* hasMixedScriptToken */ <= 0.500000) {
                  if (features[13] /* nonAsciiRatio */ <= 0.392081) {
                    if (features[13] /* nonAsciiRatio */ <= 0.387960) {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[10] /* avgTokenLength */ <= 6.541667) {
                    if (features[10] /* avgTokenLength */ <= 4.625000) {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              }
            }
          } else {
            if (features[13] /* nonAsciiRatio */ <= 0.613248) {
              if (features[14] /* hasNonLatinScript */ <= 0.500000) {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
                  if (features[11] /* uppercaseRatio */ <= 0.012821) {
                    if (features[9] /* tokenCount */ <= 3.500000) {
                      return { mode: 'semantic', confidence: 0.9763, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 0.8349, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[3] /* hasConsecutiveUppercase */ <= 0.500000) {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                } else {
                  return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            } else {
              if (features[13] /* nonAsciiRatio */ <= 0.787138) {
                if (features[10] /* avgTokenLength */ <= 6.291667) {
                  if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[9] /* tokenCount */ <= 2.500000) {
                    return { mode: 'semantic', confidence: 1.0000, tier: 5, method: 'ml' };
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                }
              } else {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            }
          }
        }
      } else {
        if (features[2] /* startsWithUppercase */ <= 0.500000) {
          if (features[14] /* hasNonLatinScript */ <= 0.500000) {
            if (features[9] /* tokenCount */ <= 3.500000) {
              return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
            } else {
              if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
                if (features[10] /* avgTokenLength */ <= 7.125000) {
                  if (features[28] /* hasSemanticKeywordNonEn */ <= 0.500000) {
                    if (features[9] /* tokenCount */ <= 4.500000) {
                      return { mode: 'structural', confidence: 0.8367, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
                    if (features[18] /* hasImpactPattern */ <= 0.500000) {
                      return { mode: 'structural', confidence: 0.7407, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    if (features[10] /* avgTokenLength */ <= 7.875000) {
                      return { mode: 'hybrid', confidence: 0.8000, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  }
                }
              } else {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            }
          } else {
            return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
          }
        } else {
          if (features[9] /* tokenCount */ <= 4.500000) {
            if (features[11] /* uppercaseRatio */ <= 0.092330) {
              return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
            } else {
              if (features[13] /* nonAsciiRatio */ <= 0.068966) {
                if (features[13] /* nonAsciiRatio */ <= 0.030331) {
                  if (features[10] /* avgTokenLength */ <= 8.500000) {
                    if (features[3] /* hasConsecutiveUppercase */ <= 0.500000) {
                      return { mode: 'structural', confidence: 0.7500, tier: 5, method: 'ml' };
                    } else {
                      return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                    }
                  } else {
                    return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
                  }
                } else {
                  return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              } else {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            }
          } else {
            return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
          }
        }
      }
    } else {
      if (features[20] /* startsWithQuestionWord */ <= 0.500000) {
        if (features[22] /* hasSemanticConceptWord */ <= 0.500000) {
          if (features[10] /* avgTokenLength */ <= 8.125000) {
            if (features[13] /* nonAsciiRatio */ <= 0.958333) {
              if (features[0] /* hasCamelBoundary */ <= 0.500000) {
                return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
              }
            } else {
              if (features[10] /* avgTokenLength */ <= 7.875000) {
                return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
              } else {
                if (features[9] /* tokenCount */ <= 3.500000) {
                  return { mode: 'structural', confidence: 0.8333, tier: 5, method: 'ml' };
                } else {
                  return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
                }
              }
            }
          } else {
            return { mode: 'structural', confidence: 1.0000, tier: 5, method: 'ml' };
          }
        } else {
          return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
        }
      } else {
        return { mode: 'hybrid', confidence: 1.0000, tier: 5, method: 'ml' };
      }
    }
  }
}

export default routeQueryML;
