import { describe, expect, it, beforeEach, afterEach } from 'vitest';
import {
  applyLiSkipPolicy,
  isExcludedByConfig,
  chunkLooksGenerated,
  _internals,
} from '../../core/indexing/li-skip-policy.js';

describe('li-skip-policy', () => {
  const cleanupEnv = () => {
    delete process.env.SWEET_SEARCH_LI_SKIP_DISABLE;
    delete process.env.SWEET_SEARCH_LI_SKIP_FILE;
    delete process.env.SWEET_SEARCH_LI_MAX_FILE_TOKENS;
    _internals.resetCache();
  };
  beforeEach(cleanupEnv);
  afterEach(cleanupEnv);

  describe('isExcludedByConfig', () => {
    it('matches vendored dirs as path segments', () => {
      expect(isExcludedByConfig('src/node_modules/foo/bar.js')).toBe(true);
      expect(isExcludedByConfig('vendor/lib/x.go')).toBe(true);
      expect(isExcludedByConfig('apps/web/.next/static/chunks/page.js')).toBe(true);
      expect(isExcludedByConfig('crates/foo/target/debug/build.rs')).toBe(true);
    });
    it('does not match substrings of segments', () => {
      expect(isExcludedByConfig('src/mynode_modulesfoo/x.js')).toBe(false);
      expect(isExcludedByConfig('src/build_helpers.js')).toBe(false);
    });
    it('handles backslash-separated paths (windows)', () => {
      expect(isExcludedByConfig('src\\node_modules\\foo\\bar.js')).toBe(true);
    });
    it('matches minified / bundled / umd / iife / sourcemaps', () => {
      expect(isExcludedByConfig('static/js/jquery.min.js')).toBe(true);
      expect(isExcludedByConfig('app.bundle.js')).toBe(true);
      expect(isExcludedByConfig('foo.umd.js')).toBe(true);
      expect(isExcludedByConfig('foo.iife.js')).toBe(true);
      expect(isExcludedByConfig('vendor.js.map')).toBe(true);
    });
    it('matches named lock files', () => {
      expect(isExcludedByConfig('package-lock.json')).toBe(true);
      expect(isExcludedByConfig('yarn.lock')).toBe(true);
      expect(isExcludedByConfig('Cargo.lock')).toBe(true);
      expect(isExcludedByConfig('poetry.lock')).toBe(true);
      expect(isExcludedByConfig('pnpm-lock.yaml')).toBe(true);
      expect(isExcludedByConfig('go.sum')).toBe(true);
    });
    it('matches jest snapshots', () => {
      expect(isExcludedByConfig('__snapshots__/foo.test.js.snap')).toBe(true);
    });
    it('returns false for normal source paths', () => {
      expect(isExcludedByConfig('core/indexing/indexer-ann.js')).toBe(false);
      expect(isExcludedByConfig('src/lib/auth.ts')).toBe(false);
      expect(isExcludedByConfig('indexer-ann.js')).toBe(false);
      expect(isExcludedByConfig('Cargo.toml')).toBe(false);
      expect(isExcludedByConfig('README.md')).toBe(false);
    });
  });

  describe('chunkLooksGenerated', () => {
    it('detects @generated marker', () => {
      expect(chunkLooksGenerated('// @generated\nfunction foo() {}')).toBe(true);
    });
    it('detects "Code generated by"', () => {
      expect(chunkLooksGenerated('// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo')).toBe(true);
    });
    it('detects DO NOT EDIT', () => {
      expect(chunkLooksGenerated('// THIS FILE IS AUTOGENERATED. DO NOT EDIT.\nconst x = 1;')).toBe(true);
    });
    it('only checks the first ~500 chars', () => {
      const buried = 'x'.repeat(600) + '\n// @generated\n';
      expect(chunkLooksGenerated(buried)).toBe(false);
    });
    it('does not flag normal source', () => {
      expect(chunkLooksGenerated('export function add(a, b) { return a + b; }')).toBe(false);
    });
  });

  describe('applyLiSkipPolicy', () => {
    const mkChunk = (file, text = 'const x = 1;') => ({ file, text });

    it('skips vendored dirs', () => {
      const { kept, stats } = applyLiSkipPolicy([
        mkChunk('src/main.js'),
        mkChunk('node_modules/foo/index.js'),
        mkChunk('vendor/lib/y.go'),
      ]);
      expect(kept.length).toBe(1);
      expect(kept[0].file).toBe('src/main.js');
      expect(stats.excluded).toBe(2);
      expect(stats.totalSkipped).toBe(2);
    });

    it('skips minified + lock files', () => {
      const { kept, stats } = applyLiSkipPolicy([
        mkChunk('src/main.js'),
        mkChunk('public/jquery.min.js'),
        mkChunk('package-lock.json'),
      ]);
      expect(kept.length).toBe(1);
      expect(stats.excluded).toBe(2);
    });

    it('skips files with generated markers', () => {
      const { kept, stats } = applyLiSkipPolicy([
        mkChunk('src/main.js', 'export const x = 1;'),
        mkChunk('src/api.pb.go', '// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api'),
      ]);
      expect(kept.length).toBe(1);
      expect(kept[0].file).toBe('src/main.js');
      expect(stats.generated).toBe(1);
    });

    it('skips a file when ALL its chunks combined exceed the per-file token cap', () => {
      // Default cap = 50_000 char-tokens. 120 chunks × 2000 chars / 4 = 60_000 → over cap.
      const huge = Array.from({ length: 120 }, () => mkChunk('big.json', 'x'.repeat(2000)));
      const small = [mkChunk('src/lib.js', 'const a = 1;')];
      const { kept, stats } = applyLiSkipPolicy([...huge, ...small]);
      expect(kept.length).toBe(1);
      expect(kept[0].file).toBe('src/lib.js');
      expect(stats.huge).toBe(120);
    });

    it('respects SWEET_SEARCH_LI_MAX_FILE_TOKENS override', () => {
      process.env.SWEET_SEARCH_LI_MAX_FILE_TOKENS = '1000';
      const chunks = Array.from({ length: 5 }, () => mkChunk('src/data.json', 'x'.repeat(2000)));
      const { kept, stats } = applyLiSkipPolicy(chunks);
      expect(kept.length).toBe(0);
      expect(stats.huge).toBe(5);
    });

    it('respects SWEET_SEARCH_LI_SKIP_DISABLE=1 (returns chunks unchanged)', () => {
      process.env.SWEET_SEARCH_LI_SKIP_DISABLE = '1';
      const chunks = [
        mkChunk('node_modules/x.js'),
        mkChunk('public/jquery.min.js'),
        mkChunk('src/main.js'),
      ];
      const { kept, stats } = applyLiSkipPolicy(chunks);
      expect(kept.length).toBe(3);
      expect(stats.totalSkipped).toBe(0);
    });

    it('returns empty stats and the same array on null/undefined input', () => {
      expect(applyLiSkipPolicy(null).kept).toEqual([]);
      expect(applyLiSkipPolicy(undefined).kept).toEqual([]);
    });

    it('groups skip decisions per file (one decision applies to all that file\'s chunks)', () => {
      const chunks = [
        { file: 'node_modules/foo/x.js', text: 'a' },
        { file: 'node_modules/foo/x.js', text: 'b' },
        { file: 'node_modules/foo/x.js', text: 'c' },
      ];
      const { kept, stats } = applyLiSkipPolicy(chunks);
      expect(kept.length).toBe(0);
      expect(stats.excluded).toBe(3); // 3 chunk-counts
      expect(stats.skippedFiles).toBe(1); // 1 distinct file
    });

    it('counts kept files correctly with multiple chunks per file', () => {
      const chunks = [
        { file: 'src/a.js', text: 'a1' },
        { file: 'src/a.js', text: 'a2' },
        { file: 'src/b.js', text: 'b1' },
      ];
      const { kept, stats } = applyLiSkipPolicy(chunks);
      expect(kept.length).toBe(3);
      expect(stats.keptFiles).toBe(2);
      expect(stats.totalSkipped).toBe(0);
    });

    it('honors project-config extensions from .sweet-search.config.json via projectRoot', async () => {
      // Write a temp .sweet-search.config.json that excludes a path
      // the defaults would NOT exclude, and verify LI honors it.
      const { mkdtempSync, writeFileSync, rmSync } = await import('node:fs');
      const { join } = await import('node:path');
      const { tmpdir } = await import('node:os');
      const tmpDir = mkdtempSync(join(tmpdir(), 'li-skip-projcfg-'));
      try {
        writeFileSync(
          join(tmpDir, '.sweet-search.config.json'),
          JSON.stringify({ exclude: ['**/fixtures/**'] }),
        );
        _internals.resetCache(); // ensure we re-load with tmpDir as root
        const { kept, stats } = applyLiSkipPolicy(
          [
            { file: 'src/main.js', text: 'const x = 1;' },
            { file: 'tests/fixtures/big.json', text: '{"a":1}' },
          ],
          { projectRoot: tmpDir },
        );
        expect(kept.length).toBe(1);
        expect(kept[0].file).toBe('src/main.js');
        expect(stats.excluded).toBe(1);
      } finally {
        rmSync(tmpDir, { recursive: true, force: true });
      }
    });
  });
});
