import { describe, expect, it, beforeEach, afterEach } from 'vitest';
import {
  applyLiSkipPolicy,
  pathHasExcludedDir,
  basenameMatchesSkipPattern,
  chunkLooksGenerated,
} from '../../core/indexing/li-skip-policy.js';

describe('li-skip-policy', () => {
  const cleanupEnv = () => {
    delete process.env.SWEET_SEARCH_LI_SKIP_DISABLE;
    delete process.env.SWEET_SEARCH_LI_SKIP_FILE;
    delete process.env.SWEET_SEARCH_LI_MAX_FILE_TOKENS;
  };
  beforeEach(cleanupEnv);
  afterEach(cleanupEnv);

  describe('pathHasExcludedDir', () => {
    it('matches vendored dirs as path segments', () => {
      expect(pathHasExcludedDir('src/node_modules/foo/bar.js')).toBe(true);
      expect(pathHasExcludedDir('vendor/lib/x.go')).toBe(true);
      expect(pathHasExcludedDir('apps/web/.next/static/chunks/page.js')).toBe(true);
      expect(pathHasExcludedDir('crates/foo/target/debug/build.rs')).toBe(true);
    });
    it('does not match substrings of segments', () => {
      expect(pathHasExcludedDir('src/mynode_modulesfoo/x.js')).toBe(false);
      expect(pathHasExcludedDir('src/build_helpers.js')).toBe(false);
    });
    it('handles backslash-separated paths (windows)', () => {
      expect(pathHasExcludedDir('src\\node_modules\\foo\\bar.js')).toBe(true);
    });
    it('returns false for normal source paths', () => {
      expect(pathHasExcludedDir('core/indexing/indexer-ann.js')).toBe(false);
      expect(pathHasExcludedDir('src/lib/auth.ts')).toBe(false);
    });
  });

  describe('basenameMatchesSkipPattern', () => {
    it('matches minified js', () => {
      expect(basenameMatchesSkipPattern('static/js/jquery.min.js')).toBe(true);
      expect(basenameMatchesSkipPattern('app.bundle.js')).toBe(true);
      expect(basenameMatchesSkipPattern('foo.umd.js')).toBe(true);
    });
    it('matches source maps', () => {
      expect(basenameMatchesSkipPattern('vendor.js.map')).toBe(true);
    });
    it('matches lock files', () => {
      expect(basenameMatchesSkipPattern('package-lock.json')).toBe(true);
      expect(basenameMatchesSkipPattern('yarn.lock')).toBe(true);
      expect(basenameMatchesSkipPattern('Cargo.lock')).toBe(true);
      expect(basenameMatchesSkipPattern('poetry.lock')).toBe(true);
      expect(basenameMatchesSkipPattern('pnpm-lock.yaml')).toBe(true);
      expect(basenameMatchesSkipPattern('go.sum')).toBe(true);
    });
    it('matches jest snapshots', () => {
      expect(basenameMatchesSkipPattern('__snapshots__/foo.test.js.snap')).toBe(true);
    });
    it('does not match normal files', () => {
      expect(basenameMatchesSkipPattern('indexer-ann.js')).toBe(false);
      expect(basenameMatchesSkipPattern('Cargo.toml')).toBe(false);
      expect(basenameMatchesSkipPattern('README.md')).toBe(false);
    });
  });

  describe('chunkLooksGenerated', () => {
    it('detects @generated marker', () => {
      expect(chunkLooksGenerated('// @generated\nfunction foo() {}')).toBe(true);
    });
    it('detects "Code generated by"', () => {
      expect(chunkLooksGenerated('// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo')).toBe(true);
    });
    it('detects DO NOT EDIT', () => {
      expect(chunkLooksGenerated('// THIS FILE IS AUTOGENERATED. DO NOT EDIT.\nconst x = 1;')).toBe(true);
    });
    it('only checks the first ~500 chars', () => {
      // Marker buried 600+ chars in should NOT trigger
      const buried = 'x'.repeat(600) + '\n// @generated\n';
      expect(chunkLooksGenerated(buried)).toBe(false);
    });
    it('does not flag normal source', () => {
      expect(chunkLooksGenerated('export function add(a, b) { return a + b; }')).toBe(false);
    });
  });

  describe('applyLiSkipPolicy', () => {
    const mkChunk = (file, text = 'const x = 1;') => ({ file, text });

    it('skips vendored dirs', () => {
      const { kept, stats } = applyLiSkipPolicy([
        mkChunk('src/main.js'),
        mkChunk('node_modules/foo/index.js'),
        mkChunk('vendor/lib/y.go'),
      ]);
      expect(kept.length).toBe(1);
      expect(kept[0].file).toBe('src/main.js');
      expect(stats.dir).toBe(2);
      expect(stats.totalSkipped).toBe(2);
    });

    it('skips minified + lock files', () => {
      const { kept, stats } = applyLiSkipPolicy([
        mkChunk('src/main.js'),
        mkChunk('public/jquery.min.js'),
        mkChunk('package-lock.json'),
      ]);
      expect(kept.length).toBe(1);
      expect(stats.pattern).toBe(2);
    });

    it('skips files with generated markers', () => {
      const { kept, stats } = applyLiSkipPolicy([
        mkChunk('src/main.js', 'export const x = 1;'),
        mkChunk('src/api.pb.go', '// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api'),
      ]);
      expect(kept.length).toBe(1);
      expect(kept[0].file).toBe('src/main.js');
      expect(stats.generated).toBe(1);
    });

    it('skips a file when ALL its chunks combined exceed the per-file token cap', () => {
      // Default cap = 50_000 char-tokens. 120 chunks × 2000 chars / 4 = 60_000 → over cap.
      const huge = Array.from({ length: 120 }, () => mkChunk('big.json', 'x'.repeat(2000)));
      const small = [mkChunk('src/lib.js', 'const a = 1;')];
      const { kept, stats } = applyLiSkipPolicy([...huge, ...small]);
      // small file kept; the huge file should be marked huge (over the cap)
      expect(kept.length).toBe(1);
      expect(kept[0].file).toBe('src/lib.js');
      expect(stats.huge).toBe(120);
    });

    it('respects SWEET_SEARCH_LI_MAX_FILE_TOKENS override', () => {
      process.env.SWEET_SEARCH_LI_MAX_FILE_TOKENS = '1000';
      // 5 chunks × 2000 chars / 4 = 2500 tokens → over the 1000 cap
      const chunks = Array.from({ length: 5 }, () => mkChunk('src/data.json', 'x'.repeat(2000)));
      const { kept, stats } = applyLiSkipPolicy(chunks);
      expect(kept.length).toBe(0);
      expect(stats.huge).toBe(5);
    });

    it('respects SWEET_SEARCH_LI_SKIP_DISABLE=1 (returns chunks unchanged)', () => {
      process.env.SWEET_SEARCH_LI_SKIP_DISABLE = '1';
      const chunks = [
        mkChunk('node_modules/x.js'),
        mkChunk('public/jquery.min.js'),
        mkChunk('src/main.js'),
      ];
      const { kept, stats } = applyLiSkipPolicy(chunks);
      expect(kept.length).toBe(3);
      expect(stats.totalSkipped).toBe(0);
    });

    it('returns empty stats and the same array on null/undefined input', () => {
      expect(applyLiSkipPolicy(null).kept).toEqual([]);
      expect(applyLiSkipPolicy(undefined).kept).toEqual([]);
    });

    it('groups skip decisions per file (one decision applies to all that file\'s chunks)', () => {
      // 3 chunks of node_modules/foo/x.js — all should be skipped together
      const chunks = [
        { file: 'node_modules/foo/x.js', text: 'a' },
        { file: 'node_modules/foo/x.js', text: 'b' },
        { file: 'node_modules/foo/x.js', text: 'c' },
      ];
      const { kept, stats } = applyLiSkipPolicy(chunks);
      expect(kept.length).toBe(0);
      expect(stats.dir).toBe(3); // 3 chunk-counts
      expect(stats.skippedFiles).toBe(1); // 1 distinct file
    });

    it('counts kept files correctly with multiple chunks per file', () => {
      const chunks = [
        { file: 'src/a.js', text: 'a1' },
        { file: 'src/a.js', text: 'a2' },
        { file: 'src/b.js', text: 'b1' },
      ];
      const { kept, stats } = applyLiSkipPolicy(chunks);
      expect(kept.length).toBe(3);
      expect(stats.keptFiles).toBe(2);
      expect(stats.totalSkipped).toBe(0);
    });
  });
});
